/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ChristyHsu (https://sketchfab.com/ida61xq)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cozy-living-room-baked-581238dc5fda4dc990571cdc02827783
title: Cozy living room baked
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Bedroom(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/bedroom/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[-249.09, 9.57, -90.58]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={[119.57, 100, 100]}>
            <mesh geometry={nodes.Leather_Sofa_Fabric002_0.geometry} material={materials['Fabric.002']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Cube007_Material023_0.geometry} material={nodes.Cube007_Material023_0.material} />
          </group>
          <group
            position={[-98.52, 245.2, -51.76]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[21.84, 56.35, 4.89]}>
            <mesh geometry={nodes.Cube008__0.geometry} material={nodes.Cube008__0.material} />
          </group>
          <group position={[-57.13, 171.93, -508.34]} rotation={[-Math.PI / 2, 0, 0]} scale={[255.07, 192.53, 215.64]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-32.13, 156, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[227.31, 455.43, 150]}>
            <mesh
              geometry={nodes.Cube019_Birch_Wood_Flooring__English_0.geometry}
              material={materials.Birch_Wood_Flooring__English}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Cube014_Material023_0.geometry} material={nodes.Cube014_Material023_0.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Cube038_Material023_0.geometry} material={nodes.Cube038_Material023_0.material} />
          </group>
          <group
            position={[12.91, 6.74, -447.89]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={[117.23, 117.23, 117.23]}>
            <mesh geometry={nodes.Radiator002_Bras_0.geometry} material={materials.Bras} />
            <mesh
              geometry={nodes.Radiator002_Heater_Paint_0.geometry}
              material={nodes.Radiator002_Heater_Paint_0.material}
            />
            <mesh
              geometry={nodes.Radiator002_Heater_Paint_0_1.geometry}
              material={nodes.Radiator002_Heater_Paint_0_1.material}
            />
            <mesh geometry={nodes.Radiator002_Plastic_0.geometry} material={materials.Plastic} />
            <mesh geometry={nodes.Radiator002_MEtal_0.geometry} material={materials.MEtal} />
            <mesh geometry={nodes.Radiator002_Bras001_0.geometry} material={materials['Bras.001']} />
            <mesh
              geometry={nodes.Radiator002_Heater_Paint001_0.geometry}
              material={nodes.Radiator002_Heater_Paint001_0.material}
            />
            <mesh
              geometry={nodes.Radiator002_Heater_Paint001_0_1.geometry}
              material={nodes.Radiator002_Heater_Paint001_0_1.material}
            />
            <mesh geometry={nodes.Radiator002_Plastic001_0.geometry} material={materials['Plastic.001']} />
            <mesh geometry={nodes.Radiator002_MEtal001_0.geometry} material={materials['MEtal.001']} />
          </group>
          <group
            position={[44.58, 305.71, -413.12]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={[141.12, 141.12, 141.12]}>
            <mesh geometry={nodes.Cylinder008_Matt_paint_white_0.geometry} material={materials.Matt_paint_white} />
            <mesh geometry={nodes.Cylinder008_Matt_paint_black_0.geometry} material={materials.Matt_paint_black} />
          </group>
          <group position={[41.58, 153.71, -412.76]} scale={[88.72, 141.12, 141.12]}>
            <mesh geometry={nodes.CURTAIN_2008_Material001_0.geometry} material={materials['Material.001']} />
          </group>
          <group
            position={[-91.07, 36.51, -11.8]}
            rotation={[Math.PI, 0.82, -Math.PI]}
            scale={[112.84, 112.84, 112.84]}>
            <mesh geometry={nodes.Grapes_of_Wrath_Grapes_of_Wrath_0.geometry} material={materials.Grapes_of_Wrath} />
          </group>
          <group position={[-109.55, 35.22, -53.76]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
            <group position={[0.01, 0.03, 0.02]} rotation={[0.02, -0.01, -0.08]}>
              <mesh geometry={nodes.Cube017_book_cover003_0.geometry} material={materials['book_cover.003']} />
              <mesh geometry={nodes.Cube017_stacked_paper004_0.geometry} material={materials['stacked_paper.004']} />
            </group>
            <group position={[-0.01, 0, 0.04]} rotation={[0.03, -0.02, 0.09]}>
              <mesh geometry={nodes.Cube020_book_cover002_0.geometry} material={materials['book_cover.002']} />
              <mesh geometry={nodes.Cube020_stacked_paper003_0.geometry} material={materials['stacked_paper.003']} />
            </group>
            <group position={[0.02, 0.02, 0]} rotation={[0.01, -0.03, 0.14]}>
              <mesh geometry={nodes.Cube029_book_cover005_0.geometry} material={materials['book_cover.005']} />
              <mesh geometry={nodes.Cube029_stacked_paper006_0.geometry} material={materials['stacked_paper.006']} />
            </group>
            <group position={[-0.02, 0, 0.07]} rotation={[0.03, -0.02, 0.24]}>
              <mesh geometry={nodes.Cube030_book_cover001_0.geometry} material={materials['book_cover.001']} />
              <mesh geometry={nodes.Cube030_stacked_paper002_0.geometry} material={materials['stacked_paper.002']} />
            </group>
            <group position={[0.01, 0.01, 0.01]} rotation={[0.01, 0, 0.06]}>
              <mesh geometry={nodes.Cube031_book_cover004_0.geometry} material={materials['book_cover.004']} />
              <mesh geometry={nodes.Cube031_stacked_paper005_0.geometry} material={materials['stacked_paper.005']} />
            </group>
            <group position={[-0.02, -0.01, 0.09]} rotation={[0.03, -0.02, 0]}>
              <mesh geometry={nodes.Cube033_book_cover_0.geometry} material={materials.book_cover} />
              <mesh geometry={nodes.Cube033_stacked_paper001_0.geometry} material={materials['stacked_paper.001']} />
            </group>
          </group>
          <group position={[-81.81, 38.76, -19.75]} rotation={[-Math.PI / 2, 0, -0.06]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Verre_Fabric_Upholstery_001a001_0.geometry}
              material={materials['Fabric_Upholstery_001a.001']}
            />
          </group>
          <group position={[-81.86, 44.52, -19.73]} rotation={[0, 0, Math.PI]} scale={[100, 100, 100]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-81.83, 40.02, -19.79]} rotation={[-Math.PI / 2, -0.3, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes['M��che_Lampion_-_m��che_0'].geometry} material={materials['Lampion_-_mche']} />
          </group>
          <group position={[-81.76, 40.67, -19.79]} scale={[100, 100, 100]}>
            <mesh geometry={nodes['Flamme_Lampion_-_Flamme_0'].geometry} material={materials['Lampion_-_Flamme']} />
          </group>
          <group position={[-81.83, 39.6, -19.79]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes['Cire_Lampion_-_Cire_0'].geometry} material={materials['Lampion_-_Cire']} />
          </group>
          <group position={[-81.83, 39.6, -19.79]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes['Alu_Lampion_-_Alu_0'].geometry} material={materials['Lampion_-_Alu']} />
          </group>
          <group position={[-52.69, 8.66, -217.25]} rotation={[-Math.PI / 2, 0, -0.77]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Cylinder_Material012_0.geometry} material={materials['Material.012']} />
            <group rotation={[1.48, 0, -Math.PI]}>
              <mesh geometry={nodes.Cube034_Fabric001_0.geometry} material={nodes.Cube034_Fabric001_0.material} />
            </group>
            <group rotation={[-0.17, 0, 0]}>
              <mesh geometry={nodes.Cube035_Fabric001_0.geometry} material={nodes.Cube035_Fabric001_0.material} />
            </group>
            <group rotation={[-0.17, 0, 0]}>
              <mesh geometry={nodes.Cube036_Material002_0.geometry} material={materials['Material.002']} />
            </group>
            <mesh geometry={nodes.Chair_Material010_0.geometry} material={materials['Material.010']} />
          </group>
          <group position={[-43.77, 69.67, -204.95]} rotation={[-0.57, -0.51, -3]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Pillow_migramah_Tecido_0.geometry}
              material={nodes.Pillow_migramah_Tecido_0.material}
            />
            <mesh
              geometry={nodes.Pillow_migramah_Tecido_0_1.geometry}
              material={nodes.Pillow_migramah_Tecido_0_1.material}
            />
            <mesh
              geometry={nodes.Pillow_migramah_Tecido_0_2.geometry}
              material={nodes.Pillow_migramah_Tecido_0_2.material}
            />
            <mesh
              geometry={nodes.Pillow_migramah_Tecido_0_3.geometry}
              material={nodes.Pillow_migramah_Tecido_0_3.material}
            />
            <mesh
              geometry={nodes.Pillow_migramah_Tecido_0_4.geometry}
              material={nodes.Pillow_migramah_Tecido_0_4.material}
            />
            <mesh
              geometry={nodes.Pillow_migramah_Tecido_0_5.geometry}
              material={nodes.Pillow_migramah_Tecido_0_5.material}
            />
          </group>
          <group position={[-84.74, 29.02, 60.76]} rotation={[-1.31, 1.16, -1.22]} scale={[60.37, 75.37, 75.37]}>
            <mesh
              geometry={nodes.Pillow_migramah001_Tecido003_0.geometry}
              material={nodes.Pillow_migramah001_Tecido003_0.material}
            />
            <mesh
              geometry={nodes.Pillow_migramah001_Tecido003_0_1.geometry}
              material={nodes.Pillow_migramah001_Tecido003_0_1.material}
            />
            <mesh
              geometry={nodes.Pillow_migramah001_Tecido003_0_2.geometry}
              material={nodes.Pillow_migramah001_Tecido003_0_2.material}
            />
            <mesh
              geometry={nodes.Pillow_migramah001_Tecido003_0_3.geometry}
              material={nodes.Pillow_migramah001_Tecido003_0_3.material}
            />
            <mesh geometry={nodes.Pillow_migramah001_Tecido004_0.geometry} material={materials['Tecido.004']} />
          </group>
          <group position={[-256.32, 137.06, -293.32]} rotation={[0, -0.31, -Math.PI]} scale={[105.58, 105.58, 105.58]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-256.27, 109.19, -293.48]} rotation={[-2.95, -0.47, -1.48]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.NurbsPath012_Metal08_PBR_0.geometry} material={materials.Metal08_PBR} />
          </group>
          <group position={[-257.14, 132.1, -290.73]} rotation={[-Math.PI / 2, 0, -0.31]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Cube018_Metal_scratched001_0.geometry} material={materials['Metal_scratched.001']} />
          </group>
          <group position={[-256.4, 109.16, -293.29]} rotation={[-1.57, 0, 1.28]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Cube023_Metal_scratched002_0.geometry} material={materials['Metal_scratched.002']} />
          </group>
          <group position={[-256.32, 136.34, -293.32]} rotation={[-Math.PI / 2, 0, -0.83]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Circle006_Metal_scratched_0.geometry} material={materials.Metal_scratched} />
          </group>
          <group position={[-256.32, 136.31, -293.32]} rotation={[-Math.PI / 2, 0, -0.83]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Circle005_Leather_Fabric_01_0.geometry} material={materials.Leather_Fabric_01} />
          </group>
          <group position={[-259.44, 131.76, -283.51]} rotation={[-0.5, -0.31, 1.41]} scale={[0.49, 0.49, 0.49]}>
            <mesh geometry={nodes.Circle002__0.geometry} material={nodes.Circle002__0.material} />
          </group>
          <group position={[-255.96, 102.32, -294.28]} rotation={[-2.61, -0.46, -1.31]} scale={[0.49, 0.49, 0.49]}>
            <mesh geometry={nodes.Circle_Old_Wood_procedural_2_0.geometry} material={materials.Old_Wood_procedural_2} />
          </group>
          <group position={[-38.31, 229.97, -90.43]} rotation={[0, -0.31, -Math.PI]} scale={[105.58, 105.58, 105.58]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-84.37, 34.35, -77.04]} rotation={[-Math.PI / 2, 0, 0.72]} scale={[146.48, 146.48, 146.48]}>
            <group position={[0, 0, 0.01]} rotation={[0, 0, 0.11]}>
              <mesh
                geometry={nodes['Metal_Support_Coffee_Cup_-_Metal_0'].geometry}
                material={materials['Coffee_Cup_-_Metal']}
              />
            </group>
            <group position={[0, 0, 0.03]}>
              <mesh
                geometry={nodes['Glass_Coffee_Cup_-_Glass_0'].geometry}
                material={materials['Coffee_Cup_-_Glass']}
              />
            </group>
            <group position={[0, 0, 0.02]}>
              <mesh geometry={nodes['Foam_Coffee_Cup_-_Foam_0'].geometry} material={materials['Coffee_Cup_-_Foam']} />
            </group>
            <group position={[0, 0, 0.02]}>
              <mesh
                geometry={nodes['Coffee_Coffee_Cup_-_Coffee_0'].geometry}
                material={materials['Coffee_Cup_-_Coffee']}
              />
            </group>
          </group>
          <group position={[-82.28, 8.72, 61.98]} rotation={[-Math.PI / 2, 0, 0.61]} scale={[157.57, 157.57, 157.57]}>
            <mesh
              geometry={nodes['Straw_basket-02_rattan_0'].geometry}
              material={nodes['Straw_basket-02_rattan_0'].material}
            />
            <mesh
              geometry={nodes['Straw_basket-02_rattan_0_1'].geometry}
              material={nodes['Straw_basket-02_rattan_0_1'].material}
            />
            <mesh
              geometry={nodes['Straw_basket-02_rattan_0_2'].geometry}
              material={nodes['Straw_basket-02_rattan_0_2'].material}
            />
            <mesh
              geometry={nodes['Straw_basket-02_rattan_0_3'].geometry}
              material={nodes['Straw_basket-02_rattan_0_3'].material}
            />
            <mesh
              geometry={nodes['Straw_basket-02_rattan_0_4'].geometry}
              material={nodes['Straw_basket-02_rattan_0_4'].material}
            />
            <mesh
              geometry={nodes['Straw_basket-02_rattan_0_5'].geometry}
              material={nodes['Straw_basket-02_rattan_0_5'].material}
            />
            <mesh
              geometry={nodes['Straw_basket-02_rattan_0_6'].geometry}
              material={nodes['Straw_basket-02_rattan_0_6'].material}
            />
          </group>
          <group position={[-72.46, 31.87, 73.94]} rotation={[-0.08, 0.68, 0.06]} scale={[124.08, 124.08, 124.08]}>
            <mesh
              geometry={nodes.Round_Towel_Hanger_2_Round_Towel_Hanger_Fabric_0.geometry}
              material={nodes.Round_Towel_Hanger_2_Round_Towel_Hanger_Fabric_0.material}
            />
            <mesh
              geometry={nodes.Round_Towel_Hanger_2_Round_Towel_Hanger_Fabric_0_1.geometry}
              material={nodes.Round_Towel_Hanger_2_Round_Towel_Hanger_Fabric_0_1.material}
            />
          </group>
          <group position={[-108.56, 61.61, -92.21]} rotation={[-1.55, 0.42, -3.14]} scale={[157.56, 126.29, 246.2]}>
            <mesh
              geometry={nodes.SM_Jug_of_flowers_A001_Material007_0.geometry}
              material={nodes.SM_Jug_of_flowers_A001_Material007_0.material}
            />
            <mesh
              geometry={nodes.SM_Jug_of_flowers_A001_Material007_0_1.geometry}
              material={nodes.SM_Jug_of_flowers_A001_Material007_0_1.material}
            />
          </group>
          <group position={[-99.94, 33.32, -53.9]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Cube021_Material009_0.geometry} material={materials['Material.009']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Plane001_Material011_0.geometry} material={materials['Material.011']} />
            <mesh geometry={nodes.Plane001_Material013_0.geometry} material={materials['Material.013']} />
          </group>
          <group position={[-108.7, 41.62, -90.87]} rotation={[-Math.PI / 2, 0, 0]} scale={[143.12, 143.12, 121.19]}>
            <mesh geometry={nodes.Sphere_Material003_0.geometry} material={materials['Material.003']} />
          </group>
          <group position={[-39.22, 239.82, -90.1]} rotation={[-Math.PI / 2, 0, 0]} scale={[31.62, 31.62, 16.07]}>
            <mesh
              geometry={nodes.Sphere001_Leather_Fabric_01002_0.geometry}
              material={materials['Leather_Fabric_01.002']}
            />
          </group>
          <group position={[-174.88, 118.7, -18.32]} rotation={[-2.75, -0.03, 2.07]} scale={[43.36, 78.8, 78.8]}>
            <mesh geometry={nodes.Plane002_Tecido005_0.geometry} material={materials['Tecido.005']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Plane_Material021_0.geometry} material={materials['Material.021']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.NurbsPath_Material008_0.geometry} material={materials['Material.008']} />
          </group>
          <group position={[-14.56, 160.38, -690.78]} scale={[393.61, 262.14, 163.94]}>
            <mesh geometry={nodes.Plane003_Material004_0.geometry} material={materials['Material.004']} />
          </group>
          <group position={[-34.49, 170.73, 274.1]} scale={100}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/bedroom/scene.gltf')
