/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Koekphon (https://sketchfab.com/acokirito)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/concert-stage-4f0cbcb0b1b64d5e88ec1122e23d9d4c
title: Concert Stage
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ConcertStage(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/concert_stage/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={nodes.Object_2.material} />
        <mesh geometry={nodes.Object_3.geometry} material={nodes.Object_3.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/concert_stage/scene.gltf')
