/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: gabrielmendesm (https://sketchfab.com/gabrielmendesm)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/female-low-poly-game-character-54a4203e58cf464eb57d68bea90e8598
title: Female Low Poly Game Character
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Female(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/female/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.corpo004_cabeloM2_0.geometry} material={materials.cabeloM2} >
              <meshStandardMaterial color={"#000"} />
            </mesh>
            <mesh geometry={nodes.corpo004_calcaM2_0.geometry} material={materials.calcaM2} />
            <mesh geometry={nodes.corpo004_blusaM2_0.geometry} material={materials.blusaM2} />
            <mesh geometry={nodes.corpo004_peleM2_0.geometry} material={materials.peleM2} />
            <mesh geometry={nodes.corpo004_sapatoM2_0.geometry} material={materials.sapatoM2} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/female/scene.gltf')
