/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: dylanheyes (https://sketchfab.com/dylanheyes)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/neon-bedroom-cece4d1882994721811afdd500d8bcf3
title: Neon Bedroom
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function NeonBedroom(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/NeonBedroom/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.71}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[252, 324, 180]}>
            <mesh geometry={nodes.Neon_Bedroom_Structure_0.geometry} material={materials.Structure} />
            <mesh geometry={nodes.Neon_Bedroom_Backdrop_0.geometry} material={materials.Backdrop} />
            <mesh geometry={nodes.Neon_Bedroom_Bed_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Neon_Bedroom_SkirtingBoard_0.geometry} material={materials.SkirtingBoard} />
            <mesh geometry={nodes.Neon_Bedroom_EndLamps_0.geometry} material={materials.EndLamps} />
            <mesh geometry={nodes.Neon_Bedroom_Carpet_0.geometry} material={materials.Carpet} />
            <mesh geometry={nodes.Neon_Bedroom_Lights_0.geometry} material={materials.Lights} />
            <mesh geometry={nodes.Neon_Bedroom_NeonText_0.geometry} material={materials.NeonText} />
            <mesh geometry={nodes.Neon_Bedroom_Mirrors_0.geometry} material={materials.Mirrors} />
            <mesh geometry={nodes.Neon_Bedroom_Trinkets_0.geometry} material={materials.Trinkets} />
            <mesh geometry={nodes.Neon_Bedroom_Seats_0.geometry} material={materials.Seats} />
            <mesh geometry={nodes.Neon_Bedroom_Dresser_0.geometry} material={materials.Dresser} />
            <mesh geometry={nodes.Neon_Bedroom_Windows_0.geometry} material={materials.Windows} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/NeonBedroom/scene.gltf')
