/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: MozillaHubs (https://sketchfab.com/mozillareality)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/nightclub-a6f7bef664274cb498963177c48e7e96
title: Nightclub
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Nightclub(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/nightclub/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.lambert2} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.lambert1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/nightclub/scene.gltf')
