/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: combine_soldier (https://sketchfab.com/combine_soldier)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/park-93f9838bf1d34b5bbcb878948a296827
title: Park
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Park(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/park/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.12}>
        <group position={[0, 0, 0.01]}>
          <mesh geometry={nodes.Plane_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.003']} />
        </group>
        <group position={[0, 1.56, 0.06]} rotation={[1.57, 1.48, 0]} scale={[0.02, 0.02, 0.03]}>
          <mesh geometry={nodes.Plane002_0.geometry} material={nodes.Plane002_0.material} />
          <mesh geometry={nodes.Plane002_1.geometry} material={nodes.Plane002_1.material} />
          <mesh geometry={nodes.Plane002_2.geometry} material={nodes.Plane002_2.material} />
        </group>
        <group scale={52.9}>
          <mesh geometry={nodes.Plane001_0.geometry} material={materials['Material.001']} />
        </group>
        <group rotation={[0.04, -0.79, -2.63]} />
        <group position={[0.91, 1.46, 0.06]} rotation={[1.57, 1.47, 0]} scale={[0.02, 0.02, 0.03]}>
          <mesh geometry={nodes.Plane003_0.geometry} material={nodes.Plane003_0.material} />
          <mesh geometry={nodes.Plane003_1.geometry} material={nodes.Plane003_1.material} />
          <mesh geometry={nodes.Plane003_2.geometry} material={nodes.Plane003_2.material} />
        </group>
        <group position={[-4.9, 2, 0.06]} rotation={[1.57, 1.52, 0]} scale={[0.02, 0.02, 0.03]}>
          <mesh geometry={nodes.Plane004_0.geometry} material={nodes.Plane004_0.material} />
          <mesh geometry={nodes.Plane004_1.geometry} material={nodes.Plane004_1.material} />
          <mesh geometry={nodes.Plane004_2.geometry} material={nodes.Plane004_2.material} />
        </group>
        <group position={[-5.82, 2.06, 0.06]} rotation={[1.57, 1.53, 0]} scale={[0.02, 0.02, 0.03]}>
          <mesh geometry={nodes.Plane005_0.geometry} material={nodes.Plane005_0.material} />
          <mesh geometry={nodes.Plane005_1.geometry} material={nodes.Plane005_1.material} />
          <mesh geometry={nodes.Plane005_2.geometry} material={nodes.Plane005_2.material} />
        </group>
        <group position={[-12.09, 1.87, 0.06]} rotation={[-1.57, 1.48, 3.14]} scale={[0.02, 0.02, 0.03]}>
          <mesh geometry={nodes.Plane006_0.geometry} material={nodes.Plane006_0.material} />
          <mesh geometry={nodes.Plane006_1.geometry} material={nodes.Plane006_1.material} />
          <mesh geometry={nodes.Plane006_2.geometry} material={nodes.Plane006_2.material} />
        </group>
        <group position={[-11.17, 1.93, 0.06]} rotation={[-1.57, 1.49, 3.14]} scale={[0.02, 0.02, 0.03]}>
          <mesh geometry={nodes.Plane007_0.geometry} material={nodes.Plane007_0.material} />
          <mesh geometry={nodes.Plane007_1.geometry} material={nodes.Plane007_1.material} />
          <mesh geometry={nodes.Plane007_2.geometry} material={nodes.Plane007_2.material} />
        </group>
        <group position={[-18.53, 0.59, 0.06]} rotation={[-1.57, 1.23, 3.14]} scale={[0.02, 0.02, 0.03]}>
          <mesh geometry={nodes.Plane008_0.geometry} material={nodes.Plane008_0.material} />
          <mesh geometry={nodes.Plane008_1.geometry} material={nodes.Plane008_1.material} />
          <mesh geometry={nodes.Plane008_2.geometry} material={nodes.Plane008_2.material} />
        </group>
        <group position={[-19.4, 0.3, 0.06]} rotation={[-1.57, 1.23, -Math.PI]} scale={[0.02, 0.02, 0.03]}>
          <mesh geometry={nodes.Plane009_0.geometry} material={nodes.Plane009_0.material} />
          <mesh geometry={nodes.Plane009_1.geometry} material={nodes.Plane009_1.material} />
          <mesh geometry={nodes.Plane009_2.geometry} material={nodes.Plane009_2.material} />
        </group>
        <group position={[-23.68, -1.78, 0.06]} rotation={[-1.57, 1.03, Math.PI]} scale={[0.02, 0.02, 0.03]}>
          <mesh geometry={nodes.Plane010_0.geometry} material={nodes.Plane010_0.material} />
          <mesh geometry={nodes.Plane010_1.geometry} material={nodes.Plane010_1.material} />
          <mesh geometry={nodes.Plane010_2.geometry} material={nodes.Plane010_2.material} />
        </group>
        <group position={[-22.89, -1.32, 0.06]} rotation={[-1.57, 1.04, Math.PI]} scale={[0.02, 0.02, 0.03]}>
          <mesh geometry={nodes.Plane011_0.geometry} material={nodes.Plane011_0.material} />
          <mesh geometry={nodes.Plane011_1.geometry} material={nodes.Plane011_1.material} />
          <mesh geometry={nodes.Plane011_2.geometry} material={nodes.Plane011_2.material} />
        </group>
        <group position={[-2.11, -1.56, 0]} rotation={[Math.PI / 2, 0, 0]} scale={2.22}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz_0.material}
          />
        </group>
        <group position={[-0.67, -1.46, 0]} rotation={[Math.PI / 2, -0.35, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz001_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz001_0.material}
          />
        </group>
        <group position={[-24.06, 4.12, 0]} rotation={[Math.PI / 2, -0.1, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz002_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz002_0.material}
          />
        </group>
        <group position={[-24.92, 2.77, 0]} rotation={[Math.PI / 2, -0.35, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz003_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz003_0.material}
          />
        </group>
        <group position={[-26.51, 3.97, 0]} rotation={[Math.PI / 2, -0.35, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz004_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz004_0.material}
          />
        </group>
        <group position={[-26.99, 0.03, 0]} rotation={[Math.PI / 2, 0.09, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz005_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz005_0.material}
          />
        </group>
        <group position={[-28.05, -2.43, 0]} rotation={[Math.PI / 2, -0.35, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz006_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz006_0.material}
          />
        </group>
        <group position={[-21.55, 5.46, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz007_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz007_0.material}
          />
        </group>
        <group position={[-24.1, -8.01, 0]} rotation={[Math.PI / 2, -0.35, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz008_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz008_0.material}
          />
        </group>
        <group position={[-25.11, -11.86, 0]} rotation={[Math.PI / 2, -0.35, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz009_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz009_0.material}
          />
        </group>
        <group position={[-5.4, -3.54, 0]} rotation={[Math.PI / 2, 0, 0]} scale={2.53}>
          <mesh
            geometry={nodes['trees-no-background-png-for-photoshop_246321_0'].geometry}
            material={nodes['trees-no-background-png-for-photoshop_246321_0'].material}
          />
        </group>
        <group position={[-7.88, -4.18, 0]} rotation={[Math.PI / 2, 0.77, 0]} scale={[2.69, 2.69, 2.69]}>
          <mesh
            geometry={nodes['trees-no-background-png-for-photoshop_246321001_0'].geometry}
            material={nodes['trees-no-background-png-for-photoshop_246321001_0'].material}
          />
        </group>
        <group position={[-21.83, -6.93, 0]} rotation={[Math.PI / 2, 0, 0]} scale={2.69}>
          <mesh
            geometry={nodes['trees-no-background-png-for-photoshop_246321002_0'].geometry}
            material={nodes['trees-no-background-png-for-photoshop_246321002_0'].material}
          />
        </group>
        <group position={[-22.86, -8.89, 0]} rotation={[Math.PI / 2, -0.4, 0]} scale={[2.69, 2.69, 2.69]}>
          <mesh
            geometry={nodes['trees-no-background-png-for-photoshop_246321003_0'].geometry}
            material={nodes['trees-no-background-png-for-photoshop_246321003_0'].material}
          />
        </group>
        <group position={[-27.62, 6.27, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz010_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz010_0.material}
          />
        </group>
        <group position={[-28.37, 5.18, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz011_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz011_0.material}
          />
        </group>
        <group position={[-27.9, 3.96, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz012_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz012_0.material}
          />
        </group>
        <group position={[-29.17, 3.1, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz013_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz013_0.material}
          />
        </group>
        <group position={[-28.48, 1.89, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz014_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz014_0.material}
          />
        </group>
        <group position={[-29.75, 1.02, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz015_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz015_0.material}
          />
        </group>
        <group position={[-28.83, -0.19, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz016_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz016_0.material}
          />
        </group>
        <group position={[-30.5, -1.35, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz017_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz017_0.material}
          />
        </group>
        <group position={[-29.23, -2.27, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz018_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz018_0.material}
          />
        </group>
        <group position={[-30.85, -3.08, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz019_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz019_0.material}
          />
        </group>
        <group position={[-29.58, -4.52, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz020_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz020_0.material}
          />
        </group>
        <group position={[-31.66, -5.62, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz021_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz021_0.material}
          />
        </group>
        <group position={[-34.97, -6.46, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz022_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz022_0.material}
          />
        </group>
        <group position={[-35.08, -8.13, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz023_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz023_0.material}
          />
        </group>
        <group position={[-37.8, -8.88, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz024_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz024_0.material}
          />
        </group>
        <group position={[-35.95, -10.9, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz025_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz025_0.material}
          />
        </group>
        <group position={[-37.1, -13.04, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz026_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz026_0.material}
          />
        </group>
        <group position={[-35.6, -14.08, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz027_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz027_0.material}
          />
        </group>
        <group position={[-34.1, -1, 0]} rotation={[-Math.PI / 2, 1.53, -Math.PI]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz028_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz028_0.material}
          />
        </group>
        <group position={[-33.96, -2.82, 0]} rotation={[-Math.PI / 2, 1.53, -Math.PI]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz029_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz029_0.material}
          />
        </group>
        <group position={[-36.35, -3.27, 0]} rotation={[-Math.PI / 2, 1.53, -Math.PI]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz030_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz030_0.material}
          />
        </group>
        <group position={[-36.76, -5.97, 0]} rotation={[-Math.PI / 2, 1.53, -Math.PI]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz031_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz031_0.material}
          />
        </group>
        <group position={[-39.05, -4.34, 0]} rotation={[-Math.PI / 2, 1.53, -Math.PI]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz032_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz032_0.material}
          />
        </group>
        <group position={[-40.42, -5.3, 0]} rotation={[-Math.PI / 2, 1.53, -Math.PI]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz033_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz033_0.material}
          />
        </group>
        <group position={[-30.47, 4.63, 0]} rotation={[Math.PI / 2, -1.49, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz034_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz034_0.material}
          />
        </group>
        <group position={[-31.81, 3.61, 0]} rotation={[Math.PI / 2, -1.49, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz035_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz035_0.material}
          />
        </group>
        <group position={[-34.16, 5.16, 0]} rotation={[Math.PI / 2, -1.49, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz036_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz036_0.material}
          />
        </group>
        <group position={[-34.47, 2.44, 0]} rotation={[Math.PI / 2, -1.49, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz037_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz037_0.material}
          />
        </group>
        <group position={[-36.83, 1.9, 0]} rotation={[Math.PI / 2, -1.49, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz038_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz038_0.material}
          />
        </group>
        <group position={[-36.63, 0.09, 0]} rotation={[Math.PI / 2, -1.49, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz039_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz039_0.material}
          />
        </group>
        <group position={[-24.16, -10.19, 0]} rotation={[Math.PI / 2, -1.49, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz040_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz040_0.material}
          />
        </group>
        <group position={[-24.36, -8.37, 0]} rotation={[Math.PI / 2, -1.49, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz041_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz041_0.material}
          />
        </group>
        <group position={[-21.99, -7.84, 0]} rotation={[Math.PI / 2, -1.49, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz042_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz042_0.material}
          />
        </group>
        <group position={[-21.69, -5.11, 0]} rotation={[Math.PI / 2, -1.49, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz043_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz043_0.material}
          />
        </group>
        <group position={[-19.34, -6.66, 0]} rotation={[Math.PI / 2, -1.49, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz044_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz044_0.material}
          />
        </group>
        <group position={[-18, -5.65, 0]} rotation={[Math.PI / 2, -1.49, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz045_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz045_0.material}
          />
        </group>
        <group position={[-27.95, -15.58, 0]} rotation={[-Math.PI / 2, 1.53, -Math.PI]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz046_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz046_0.material}
          />
        </group>
        <group position={[-24.29, -16.25, 0]} rotation={[-Math.PI / 2, 1.53, -Math.PI]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz048_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz048_0.material}
          />
        </group>
        <group position={[-23.88, -13.54, 0]} rotation={[-Math.PI / 2, 1.53, -Math.PI]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz049_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz049_0.material}
          />
        </group>
        <group position={[-21.49, -13.09, 0]} rotation={[-Math.PI / 2, 1.53, -Math.PI]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz050_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz050_0.material}
          />
        </group>
        <group position={[-21.63, -11.27, 0]} rotation={[-Math.PI / 2, 1.53, -Math.PI]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz051_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz051_0.material}
          />
        </group>
        <group position={[-23.13, -24.36, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz052_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz052_0.material}
          />
        </group>
        <group position={[-24.63, -23.32, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz053_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz053_0.material}
          />
        </group>
        <group position={[-23.48, -21.18, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz054_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz054_0.material}
          />
        </group>
        <group position={[-25.32, -19.16, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz055_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz055_0.material}
          />
        </group>
        <group position={[-22.61, -18.41, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz056_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz056_0.material}
          />
        </group>
        <group position={[-22.49, -16.73, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz057_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz057_0.material}
          />
        </group>
        <group position={[-19.19, -15.9, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz058_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz058_0.material}
          />
        </group>
        <group position={[-17.11, -14.8, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz059_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz059_0.material}
          />
        </group>
        <group position={[-18.38, -13.36, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz060_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz060_0.material}
          />
        </group>
        <group position={[-16.76, -12.55, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz061_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz061_0.material}
          />
        </group>
        <group position={[-18.03, -11.62, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz062_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz062_0.material}
          />
        </group>
        <group position={[-16.36, -10.47, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz063_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz063_0.material}
          />
        </group>
        <group position={[-17.28, -9.26, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz064_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz064_0.material}
          />
        </group>
        <group position={[-16.01, -8.39, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz065_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz065_0.material}
          />
        </group>
        <group position={[-16.7, -7.18, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz066_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz066_0.material}
          />
        </group>
        <group position={[-15.43, -6.31, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz067_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz067_0.material}
          />
        </group>
        <group position={[-15.9, -5.1, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz068_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz068_0.material}
          />
        </group>
        <group position={[-15.14, -4, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz069_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz069_0.material}
          />
        </group>
        <group position={[-9.08, -4.81, 0]} rotation={[Math.PI / 2, -0.64, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz070_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz070_0.material}
          />
        </group>
        <group position={[-15.58, -12.7, 0]} rotation={[Math.PI / 2, -0.35, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz071_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz071_0.material}
          />
        </group>
        <group position={[-14.52, -10.25, 0]} rotation={[Math.PI / 2, 0.09, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz072_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz072_0.material}
          />
        </group>
        <group position={[-14.04, -6.3, 0]} rotation={[Math.PI / 2, -0.35, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz073_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz073_0.material}
          />
        </group>
        <group position={[-12.45, -7.51, 0]} rotation={[Math.PI / 2, -0.35, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz074_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz074_0.material}
          />
        </group>
        <group position={[-11.58, -6.16, 0]} rotation={[Math.PI / 2, -0.1, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz075_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz075_0.material}
          />
        </group>
        <group position={[-32.06, 2.48, 0]} rotation={[Math.PI / 2, 0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz076_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz076_0.material}
          />
        </group>
        <group position={[-32.38, 0.91, 0]} rotation={[Math.PI / 2, 0.02, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz077_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz077_0.material}
          />
        </group>
        <group position={[-34.29, 1.45, 0]} rotation={[Math.PI / 2, 0.02, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz078_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz078_0.material}
          />
        </group>
        <group position={[-33.3, -2.4, 0]} rotation={[Math.PI / 2, 0.46, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz079_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz079_0.material}
          />
        </group>
        <group position={[-33.4, -5.07, 0]} rotation={[Math.PI / 2, 0.02, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz080_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz080_0.material}
          />
        </group>
        <group position={[-30.22, 4.64, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz081_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz081_0.material}
          />
        </group>
        <group position={[-36.16, 3.19, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz082_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz082_0.material}
          />
        </group>
        <group position={[-36.46, 1.9, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz083_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz083_0.material}
          />
        </group>
        <group position={[-35.59, 0.93, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz084_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz084_0.material}
          />
        </group>
        <group position={[-36.46, -0.33, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz085_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz085_0.material}
          />
        </group>
        <group position={[-35.37, -1.21, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz086_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz086_0.material}
          />
        </group>
        <group position={[-36.24, -2.48, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz087_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz087_0.material}
          />
        </group>
        <group position={[-34.94, -3.27, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz088_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz088_0.material}
          />
        </group>
        <group position={[-36.08, -4.96, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz089_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz089_0.material}
          />
        </group>
        <group position={[-34.56, -5.36, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz090_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz090_0.material}
          />
        </group>
        <group position={[-35.77, -6.7, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz091_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz091_0.material}
          />
        </group>
        <group position={[-34.06, -7.58, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz092_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz092_0.material}
          />
        </group>
        <group position={[-35.6, -9.36, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz093_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz093_0.material}
          />
        </group>
        <group position={[-38.37, -11.34, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz094_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz094_0.material}
          />
        </group>
        <group position={[-37.87, -12.94, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz095_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz095_0.material}
          />
        </group>
        <group position={[-40.13, -14.63, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz096_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz096_0.material}
          />
        </group>
        <group position={[-37.67, -15.84, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz097_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz097_0.material}
          />
        </group>
        <group position={[-37.97, -18.25, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz098_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz098_0.material}
          />
        </group>
        <group position={[-36.19, -18.67, 0]} rotation={[Math.PI / 2, -0.27, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz099_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz099_0.material}
          />
        </group>
        <group position={[-39.56, -5.94, 0]} rotation={[-Math.PI / 2, 1.16, -Math.PI]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz100_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz100_0.material}
          />
        </group>
        <group position={[-38.77, -7.59, 0]} rotation={[-Math.PI / 2, 1.16, -Math.PI]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz101_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz101_0.material}
          />
        </group>
        <group position={[-40.83, -8.87, 0]} rotation={[-Math.PI / 2, 1.16, -Math.PI]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz102_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz102_0.material}
          />
        </group>
        <group position={[-40.22, -11.54, 0]} rotation={[-Math.PI / 2, 1.16, -Math.PI]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz103_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz103_0.material}
          />
        </group>
        <group position={[-42.95, -10.85, 0]} rotation={[-Math.PI / 2, 1.16, -Math.PI]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz104_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz104_0.material}
          />
        </group>
        <group position={[-43.88, -12.25, 0]} rotation={[-Math.PI / 2, 1.16, -Math.PI]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz105_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz105_0.material}
          />
        </group>
        <group position={[-38.22, 0.62, 0]} rotation={[Math.PI / 2, -1.12, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz106_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz106_0.material}
          />
        </group>
        <group position={[-39.1, -0.81, 0]} rotation={[Math.PI / 2, -1.12, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz107_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz107_0.material}
          />
        </group>
        <group position={[-41.85, -0.23, 0]} rotation={[Math.PI / 2, -1.12, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz108_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz108_0.material}
          />
        </group>
        <group position={[-41.15, -2.87, 0]} rotation={[Math.PI / 2, -1.12, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz109_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz109_0.material}
          />
        </group>
        <group position={[-43.16, -4.23, 0]} rotation={[Math.PI / 2, -1.12, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz110_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz110_0.material}
          />
        </group>
        <group position={[-26.58, -14.61, 0]} rotation={[-Math.PI / 2, 1.53, -Math.PI]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz047_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz047_0.material}
          />
        </group>
        <group position={[-29.72, 11.83, 0]} rotation={[-Math.PI / 2, -1.13, -Math.PI]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz112_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz112_0.material}
          />
        </group>
        <group position={[-27.62, 9.96, 0]} rotation={[-Math.PI / 2, -1.13, -Math.PI]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz113_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz113_0.material}
          />
        </group>
        <group position={[-26.15, 10.77, 0]} rotation={[-Math.PI / 2, -1.13, -Math.PI]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz114_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz114_0.material}
          />
        </group>
        <group position={[-25.22, 5.76, 0]} rotation={[Math.PI / 2, -1.16, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz115_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz115_0.material}
          />
        </group>
        <group position={[-25.96, 7.09, 0]} rotation={[Math.PI / 2, -1.16, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz116_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz116_0.material}
          />
        </group>
        <group position={[-24.58, 7.77, 0]} rotation={[Math.PI / 2, -1.16, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz117_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz117_0.material}
          />
        </group>
        <group position={[-25.09, 9.07, 0]} rotation={[Math.PI / 2, -1.16, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz118_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz118_0.material}
          />
        </group>
        <group position={[-23.71, 9.74, 0]} rotation={[Math.PI / 2, -1.16, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz119_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz119_0.material}
          />
        </group>
        <group position={[-23.99, 11.01, 0]} rotation={[Math.PI / 2, -1.16, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz120_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz120_0.material}
          />
        </group>
        <group position={[-23.09, 11.99, 0]} rotation={[Math.PI / 2, -1.16, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz121_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz121_0.material}
          />
        </group>
        <group position={[-17.2, 10.31, 0]} rotation={[Math.PI / 2, -1.16, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz122_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz122_0.material}
          />
        </group>
        <group position={[-24.77, 3.44, 0]} rotation={[Math.PI / 2, -0.87, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz123_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz123_0.material}
          />
        </group>
        <group position={[-23.37, 5.72, 0]} rotation={[Math.PI / 2, -0.43, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz124_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz124_0.material}
          />
        </group>
        <group position={[-22.32, 9.55, 0]} rotation={[Math.PI / 2, -0.87, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz125_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz125_0.material}
          />
        </group>
        <group position={[-20.93, 8.13, 0]} rotation={[Math.PI / 2, -0.87, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz126_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz126_0.material}
          />
        </group>
        <group position={[-19.87, 9.34, 0]} rotation={[Math.PI / 2, -0.62, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz127_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz127_0.material}
          />
        </group>
        <group position={[-25.03, 9.52, 0]} rotation={[-Math.PI / 2, -0.76, Math.PI]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz128_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz128_0.material}
          />
        </group>
        <group position={[-24.31, 11.2, 0]} rotation={[-Math.PI / 2, -0.76, Math.PI]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz129_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz129_0.material}
          />
        </group>
        <group position={[-21.98, 10.5, 0]} rotation={[-Math.PI / 2, -0.76, Math.PI]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz130_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz130_0.material}
          />
        </group>
        <group position={[-20.37, 12.71, 0]} rotation={[-Math.PI / 2, -0.76, Math.PI]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz131_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz131_0.material}
          />
        </group>
        <group position={[-19.1, 10.2, 0]} rotation={[-Math.PI / 2, -0.76, Math.PI]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz132_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz132_0.material}
          />
        </group>
        <group position={[-17.43, 10.42, 0]} rotation={[-Math.PI / 2, -0.76, Math.PI]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz133_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz133_0.material}
          />
        </group>
        <group position={[-26.45, 6.47, 0]} rotation={[Math.PI / 2, 0.72, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz134_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz134_0.material}
          />
        </group>
        <group position={[-24.15, 5.68, 0]} rotation={[Math.PI / 2, 0.72, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz135_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz135_0.material}
          />
        </group>
        <group position={[-23.37, 7.33, 0]} rotation={[Math.PI / 2, 0.72, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz136_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz136_0.material}
          />
        </group>
        <group position={[-21.18, 2.03, 0]} rotation={[Math.PI / 2, -1.53, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz137_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz137_0.material}
          />
        </group>
        <group position={[-21.57, 3.91, 0]} rotation={[Math.PI / 2, -1.53, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz138_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz138_0.material}
          />
        </group>
        <group position={[-19.77, 3.81, 0]} rotation={[Math.PI / 2, -1.53, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz139_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz139_0.material}
          />
        </group>
        <group position={[-20.41, 5.24, 0]} rotation={[Math.PI / 2, -1.53, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz140_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz140_0.material}
          />
        </group>
        <group position={[-18.39, 5.42, 0]} rotation={[Math.PI / 2, -1.53, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz141_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz141_0.material}
          />
        </group>
        <group position={[-18.59, 6.93, 0]} rotation={[Math.PI / 2, -1.53, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz142_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz142_0.material}
          />
        </group>
        <group position={[-17.06, 7.05, 0]} rotation={[Math.PI / 2, -1.53, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz143_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz143_0.material}
          />
        </group>
        <group position={[-42.3, -5.85, 0]} rotation={[Math.PI / 2, -1.12, 0]} scale={[1.63, 1.63, 1.63]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz111_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz111_0.material}
          />
        </group>
        <group position={[-17.06, 8.45, 0]} rotation={[Math.PI / 2, -1.53, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz144_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz144_0.material}
          />
        </group>
        <group position={[-15.53, 8.58, 0]} rotation={[Math.PI / 2, -1.53, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz145_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz145_0.material}
          />
        </group>
        <group position={[-15.33, 9.86, 0]} rotation={[Math.PI / 2, -1.53, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz146_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz146_0.material}
          />
        </group>
        <group position={[-14.14, 10.44, 0]} rotation={[Math.PI / 2, -1.53, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz147_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz147_0.material}
          />
        </group>
        <group position={[-9.27, 6.74, 0]} rotation={[Math.PI / 2, -1.53, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz148_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz148_0.material}
          />
        </group>
        <group position={[-18.81, 3.09, 0]} rotation={[Math.PI / 2, -1.24, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz149_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz149_0.material}
          />
        </group>
        <group position={[-16.68, 4.7, 0]} rotation={[Math.PI / 2, -0.8, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz150_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz150_0.material}
          />
        </group>
        <group position={[-14.31, 7.89, 0]} rotation={[Math.PI / 2, -1.24, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz151_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz151_0.material}
          />
        </group>
        <group position={[-13.53, 6.06, 0]} rotation={[Math.PI / 2, -1.24, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz152_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz152_0.material}
          />
        </group>
        <group position={[-12.11, 6.81, 0]} rotation={[Math.PI / 2, -0.99, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz153_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz153_0.material}
          />
        </group>
        <group position={[-0.7, 1.71, 0]} scale={0.15}>
          <mesh geometry={nodes.Circle_0.geometry} material={nodes.Circle_0.material} />
        </group>
        <group position={[1.33, 1.48, 0]} scale={0.15}>
          <mesh geometry={nodes.Circle001_0.geometry} material={nodes.Circle001_0.material} />
        </group>
        <group position={[-4.46, 2.08, 0]} scale={0.15}>
          <mesh geometry={nodes.Circle002_0.geometry} material={nodes.Circle002_0.material} />
        </group>
        <group position={[-6.51, 2.17, 0]} scale={0.15}>
          <mesh geometry={nodes.Circle003_0.geometry} material={nodes.Circle003_0.material} />
        </group>
        <group position={[-10.77, 2.08, 0]} scale={0.15}>
          <mesh geometry={nodes.Circle004_0.geometry} material={nodes.Circle004_0.material} />
        </group>
        <group position={[-12.8, 1.89, 0]} scale={0.15}>
          <mesh geometry={nodes.Circle005_0.geometry} material={nodes.Circle005_0.material} />
        </group>
        <group position={[-18.14, 0.83, 0]} scale={0.15}>
          <mesh geometry={nodes.Circle006_0.geometry} material={nodes.Circle006_0.material} />
        </group>
        <group position={[-20.11, 0.15, 0]} scale={0.15}>
          <mesh geometry={nodes.Circle007_0.geometry} material={nodes.Circle007_0.material} />
        </group>
        <group position={[-22.57, -1.03, 0]} scale={0.15}>
          <mesh geometry={nodes.Circle008_0.geometry} material={nodes.Circle008_0.material} />
        </group>
        <group position={[-24.34, -2.09, 0]} scale={0.15}>
          <mesh geometry={nodes.Circle009_0.geometry} material={nodes.Circle009_0.material} />
        </group>
        <group position={[-1.13, -0.73, 0]} scale={0.13}>
          <mesh geometry={nodes.Circle010_0.geometry} material={nodes.Circle010_0.material} />
          <mesh geometry={nodes.Circle010_1.geometry} material={nodes.Circle010_1.material} />
        </group>
        <group position={[0.98, 1.81, -0.06]} rotation={[Math.PI / 2, -0.35, 0]} scale={[2.22, 2.22, 2.22]}>
          <mesh
            geometry={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz154_0.geometry}
            material={nodes.tn1_free_tree_texture_digitalholeinone_IMG2396_btkyz154_0.material}
          />
        </group>
        <group position={[-0.67, 2.28, 0]} scale={0.13}>
          <mesh geometry={nodes.Circle011_0.geometry} material={nodes.Circle011_0.material} />
          <mesh geometry={nodes.Circle011_1.geometry} material={nodes.Circle011_1.material} />
        </group>
        <group position={[-6.53, 2.72, 0]} rotation={[0, 0, 0.09]} scale={[0.13, 0.13, 0.13]}>
          <mesh geometry={nodes.Circle012_0.geometry} material={nodes.Circle012_0.material} />
          <mesh geometry={nodes.Circle012_1.geometry} material={nodes.Circle012_1.material} />
        </group>
        <group position={[-6.71, -0.31, 0]} rotation={[0, 0, 0.09]} scale={[0.13, 0.13, 0.13]}>
          <mesh geometry={nodes.Circle013_0.geometry} material={nodes.Circle013_0.material} />
          <mesh geometry={nodes.Circle013_1.geometry} material={nodes.Circle013_1.material} />
        </group>
        <group position={[-12.57, -0.58, 0]} rotation={[0, 0, 0.25]} scale={[0.13, 0.13, 0.13]}>
          <mesh geometry={nodes.Circle014_0.geometry} material={nodes.Circle014_0.material} />
          <mesh geometry={nodes.Circle014_1.geometry} material={nodes.Circle014_1.material} />
        </group>
        <group position={[-12.86, 2.44, 0]} rotation={[0, 0, 0.25]} scale={[0.13, 0.13, 0.13]}>
          <mesh geometry={nodes.Circle015_0.geometry} material={nodes.Circle015_0.material} />
          <mesh geometry={nodes.Circle015_1.geometry} material={nodes.Circle015_1.material} />
        </group>
        <group position={[-20.16, 0.68, 0]} rotation={[0, 0, 0.45]} scale={[0.13, 0.13, 0.13]}>
          <mesh geometry={nodes.Circle016_0.geometry} material={nodes.Circle016_0.material} />
          <mesh geometry={nodes.Circle016_1.geometry} material={nodes.Circle016_1.material} />
        </group>
        <group position={[-19.25, -2.22, 0]} rotation={[0, 0, 0.45]} scale={[0.13, 0.13, 0.13]}>
          <mesh geometry={nodes.Circle017_0.geometry} material={nodes.Circle017_0.material} />
          <mesh geometry={nodes.Circle017_1.geometry} material={nodes.Circle017_1.material} />
        </group>
        <group position={[-23.13, -4.26, 0]} rotation={[0, 0, 0.74]} scale={[0.13, 0.13, 0.13]}>
          <mesh geometry={nodes.Circle018_0.geometry} material={nodes.Circle018_0.material} />
          <mesh geometry={nodes.Circle018_1.geometry} material={nodes.Circle018_1.material} />
        </group>
        <group position={[-24.8, -1.73, 0]} rotation={[0, 0, 0.74]} scale={[0.13, 0.13, 0.13]}>
          <mesh geometry={nodes.Circle019_0.geometry} material={nodes.Circle019_0.material} />
          <mesh geometry={nodes.Circle019_1.geometry} material={nodes.Circle019_1.material} />
        </group>
        <group position={[-28.89, -6.08, 0]} rotation={[0, 0, 0.99]} scale={[0.13, 0.13, 0.13]}>
          <mesh geometry={nodes.Circle020_0.geometry} material={nodes.Circle020_0.material} />
          <mesh geometry={nodes.Circle020_1.geometry} material={nodes.Circle020_1.material} />
        </group>
        <group position={[-26.62, -8.1, 0]} rotation={[0, 0, 0.99]} scale={[0.13, 0.13, 0.13]}>
          <mesh geometry={nodes.Circle021_0.geometry} material={nodes.Circle021_0.material} />
          <mesh geometry={nodes.Circle021_1.geometry} material={nodes.Circle021_1.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/park/scene.gltf')
